GET http://localhost:3001/api/persons

###
Get http://localhost:3001/api/person/6


###
DELETE http://localhost:3001/api/person/119


###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "number": "004-123145"
}

###