// get all notes
GET http://localhost:3001/api/notes


###
// add a note 
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Ma Poppendick",
    "important": "39-23-6423122"
}

###
// add a note for bad request
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "important": "39-23-6423122"
}

###
// unknown endpoint
GET http://localhost:3001/api/
